### PR TITLE
chore: update plugin name to `auto-install-webpack-plugin`

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
update name

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
Yes
**Summary**
Update name to `auto-install-webpack-plugin`

**Does this PR introduce a breaking change?**
Yes

**Other information**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
I think was wrong :disappointed: For me better name is `install-webpack-plugin` and by default ask developer to install dep due typosquatting when you development project, and add options `ask: true`/`auto: true` to install without questions. What do you think?

For CLI I think we can implement `--install` (with question) and `--auto-install` (without question) or maybe `--install` (with question) and `--install auto`/`--install force` (without question). Need small discussion. What do you think?

**Comment by alexander-akait** [comment]
@snitin315 Let's use `install-webpack-plugin` name, feel free to update, we need do release

**Comment by snitin315** [comment]
I will update 👍

**Comment by snitin315** [comment]
> For CLI I think we can implement --install (with question) and --auto-install (without question) or maybe --install (with question) and --install auto/--install force (without question). Need small discussion. What do you think?

I think `--install` and `--install auto` are good 👍🏻.

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Now we need implement `promt` before install https://github.com/webpack-contrib/install-webpack-plugin/issues/129 (true by defaut), you can found code here https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/utils/prompt.js

**Comment by snitin315** [comment]
I will implement 👍🏻

**Pull request merged**
