### PR TITLE
feat: use default package manager from local environment

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
WIP
**If relevant, did you update the documentation?**
No
**Summary**
get package manager from the local environment.

**Does this PR introduce a breaking change?**
Yes, `npm` is no longer the default.

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Ideally we should migrate from mock in future, put `pnpm`/`yarn`/`npm` in deps and run real tests

**Comment by alexander-akait** [comment]
@snitin315 Do we have something in our roadmap for this plugin?

**Comment by snitin315** [comment]
Most of the major tasks are done. some things left 

- remove `quiet`.
- update docs.
- refactor code

**Comment by alexander-akait** [comment]
@snitin315 

> remove quiet.

Ideally we should use `info` for `important` information and `log` for `unimportant`, so developer can setup it in webpack configuration

**Comment by alexander-akait** [comment]
But we have two types of logs: from our plugin and from package manager, make sense to allow suppress logs from package manager, i.e. we need `packageManager.options.arguments: ['-d']` and it will run `npm install something -d` https://docs.npmjs.com/cli/v7/using-npm/config (and no logs will be from npm), same for other package manager

**Comment by alexander-akait** [comment]
Also it allows to pass other arguments to package manager

**Pull request merged**
