### PR TITLE
feat: use built in webpack logger

### LINKED ISSUE #94: Prefix for own logging
What do you think of prefixing the plugin's own logging with `"[NpmInstallPlugin] "` or similar so it's clear where it's coming from?

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feat, refactor

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
No
**Summary**

fixes #94 

**Does this PR introduce a breaking change?**
Maybe

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Let's fix CI

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Let's add `schema` (i.e. options.json) and validate option

**Comment by alexander-akait** [comment]
Thanks for help

**Comment by snitin315** [comment]
> @snitin315 Let's add `schema` (i.e. options.json) and validate option

On it  👍🏻

**Pull request merged**
