### PR TITLE
chore: added support for pnpm

### PR DESCRIPTION
**Pull request by anikethsaha**
- added support for pnpm
- added tests for it

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Need fix CI test

**Comment by anikethsaha** [comment]
> Need fix CI test

https://github.com/webpack-contrib/npm-install-webpack-plugin/pull/130

facing a bit issue to do spy tests for hooks...

**Comment by anikethsaha** [comment]
although this PR is nonbreaking, independent PR, the installer tests are passing as aspected.

**Comment by evilebottnawi** [comment]
Sorry, I can't merge new features with broken CI, please fix CI tests before implement new features

**Comment by evilebottnawi** [comment]
Let's keep it, we will fix CI problem in future

**Comment by snitin315** [comment]
fixed in master.

**Pull request closed without merging**
